# Generated by Django 5.2.3 on 2025-06-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmodel',
            name='created_by',
        ),
    ]
