# Generated by Django 5.2.3 on 2025-06-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurantmodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='is_votable',
            field=models.BooleanField(default=True),
        ),
    ]
