# Generated by Django 5.2.3 on 2025-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantmodel_is_votable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
