# Generated by Django 5.2.3 on 2025-06-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurantmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
