services:
  web:
    build:
      context: .
    container_name: lunch_voting_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - test
    env_file:
      - .env
    entrypoint: ["/app/entrypoint.sh"]

  redis:
    image: redis:7
    container_name: lunch_voting_redis

  celery:
    build:
      context: .
    container_name: lunch_voting_celery
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env

  celery-beat:
    build:
      context: .
    container_name: lunch_voting_celery_beat
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env

  test:
    build:
      context: .
    container_name: lunch_voting_test
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py test"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env