# Generated by Django 5.2.3 on 2025-06-28 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='restaurants.restaurantmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='voting_vote_user_id_88afd2_idx'), models.Index(fields=['restaurant', 'created_at'], name='voting_vote_restaur_3d9f7f_idx'), models.Index(fields=['created_at'], name='voting_vote_created_198428_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('created_at__date', models.F('created_at__date'))), fields=('user', 'restaurant'), name='unique_user_restaurant_per_day')],
            },
        ),
    ]
