# Generated by Django 5.2.3 on 2025-06-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='votemodel',
            name='unique_user_restaurant_per_day',
        ),
    ]
