# Generated by Django 5.2.3 on 2025-06-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_votemodel_unique_user_restaurant_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
