# Generated by Django 5.2.3 on 2025-06-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWinnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unique_voters', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantmodel')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='winners_dai_date_897fcc_idx'), models.Index(fields=['restaurant'], name='winners_dai_restaur_18b41e_idx')],
            },
        ),
    ]
