# Generated by Django 5.2.3 on 2025-06-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywinnermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
